package com.konqasasas.inputvisualizer.pack;

import com.google.gson.*; import com.konqasasas.inputvisualizer.config.*; import com.konqasasas.inputvisualizer.model.Model; import net.minecraft.client.Minecraft; import net.minecraft.client.renderer.texture.DynamicTexture; import net.minecraft.util.ResourceLocation; import org.apache.logging.log4j.LogManager; import org.apache.logging.log4j.Logger;
import javax.imageio.ImageIO; import java.awt.image.BufferedImage; import java.io.*; import java.nio.charset.StandardCharsets; import java.util.*; import java.util.zip.*;

public final class VisualizerPackManager {
    private static final String INITIAL_PACK = "aqua.ivizpack";
    private static final String[] DEFAULT_PACKS = new String[]{"amber.ivizpack","aqua.ivizpack","kawaii.ivizpack","minimal.ivizpack"};
    private static final Logger LOG=LogManager.getLogger("InputVisualizer"); private final VisualizerPaths paths; private final VisualizerSettingsManager settings; private final Gson gson=new GsonBuilder().setPrettyPrinting().create(); private VisualizerPack active; private String lastError=""; private int textureSerial=0;
    public VisualizerPackManager(VisualizerPaths p, VisualizerSettingsManager s){paths=p;settings=s;}
    public VisualizerPack active(){return active;} public String lastError(){return lastError;} public String activeStatus(){return active==null?"no active pack" : active.fileName+" roots="+(active.layout==null||active.layout.roots==null?-1:active.layout.roots.size());} public void warn(String m, Throwable t){LOG.warn(m,t);} public void warn(String m){LOG.warn(m);} public ArrayList<String> listPackNames(){ ArrayList<String> r=new ArrayList<>(); File[] fs=paths.packDir.listFiles(); if(fs!=null) for(File f:fs) if(f.isFile()&&f.getName().toLowerCase(Locale.ROOT).endsWith(".ivizpack")) r.add(f.getName()); Collections.sort(r); return r; }
    public void ensureDefaultPack(){ paths.ensureDirectories(); for(String name:DEFAULT_PACKS) ensureBundledPack(name); }
    private void ensureBundledPack(String name){ File f=new File(paths.packDir,name); if(f.isFile()) return; String res="input_visualizer/default_packs/"+name; try(InputStream in=VisualizerPackManager.class.getClassLoader().getResourceAsStream(res)){ if(in==null){ LOG.warn("bundled default pack missing: "+res); return; } try(OutputStream out=new FileOutputStream(f)){ byte[] b=new byte[8192]; int n; while((n=in.read(b))!=-1) out.write(b,0,n); } LOG.warn("created bundled input visualizer pack: "+f.getAbsolutePath()); } catch(Exception e){LOG.warn("default pack write failed: "+name,e);} }
    public void loadAtStartup(){ if("default.ivizpack".equals(settings.get().activePack)){ settings.get().activePack=INITIAL_PACK; settings.save(); } LOG.warn("loadAtStartup activePack="+settings.get().activePack+", packDir="+paths.packDir.getAbsolutePath()); if(!loadSelected(false)){ LOG.warn("initial pack load failed, falling back to "+INITIAL_PACK+"; lastError="+lastError); settings.get().activePack=INITIAL_PACK; settings.save(); loadSelected(false); } }
    public boolean reloadKeepingPrevious(){ settings.loadOrCreate(); boolean ok=loadSelected(true); if(ok) return true; return false; }
    public boolean selectPack(String name){ if(name==null||name.contains("/")||name.contains("\\")||!name.endsWith(".ivizpack")) return false; settings.get().activePack=name; settings.save(); return loadSelected(true); }
    private boolean loadSelected(boolean keepPrevious){ File target=new File(paths.packDir,settings.get().activePack); LOG.warn("trying to load input visualizer pack: "+target.getAbsolutePath()+", exists="+target.isFile()); try { VisualizerPack p=loadPack(target); if(p==null) { lastError="loadPack returned null"; LOG.warn(lastError); return false; } active=p; lastError=""; LOG.warn("loaded input visualizer pack: "+p.fileName+", roots="+(p.layout==null||p.layout.roots==null?-1:p.layout.roots.size())); return true; } catch(Exception e){ lastError=e.getMessage()==null?e.toString():e.getMessage(); LOG.warn("pack load failed: "+settings.get().activePack,e); if(!keepPrevious) active=null; return false; } }
    private VisualizerPack loadPack(File file) throws Exception { if(!file.isFile()) throw new IOException("pack not found: "+file.getName()); JsonObject bundle; HashMap<String, byte[]> textureBytes=new HashMap<>(); try(ZipFile zip=new ZipFile(file)){ ZipEntry be=zip.getEntry("bundle.json"); if(be==null) throw new IOException("bundle.json missing"); try(InputStream in=zip.getInputStream(be); Reader r=new InputStreamReader(in,StandardCharsets.UTF_8)){ JsonElement el=new JsonParser().parse(r); if(!el.isJsonObject()) throw new IOException("bundle.json root is not object"); bundle=el.getAsJsonObject(); } Enumeration<? extends ZipEntry> en=zip.entries(); while(en.hasMoreElements()){ ZipEntry ze=en.nextElement(); if(ze.isDirectory()) continue; String n=ze.getName().replace('\\','/'); if(PackPathGuard.isSafeTexturePath(n)){ try(InputStream in=zip.getInputStream(ze)){ textureBytes.put(n, readAll(in, 16*1024*1024)); } } } }
        validateHeader(bundle); PackParser parser=new PackParser(); Model.Layout layout=parser.parse(bundle); HashMap<String,LoadedPackTexture> textures=registerTextures(textureBytes, layout); for(String w:layout.warnings) LOG.warn("pack warning: "+w); return new VisualizerPack(file.getName(),bundle,layout,textures); }
    private void validateHeader(JsonObject b) throws IOException { if(!"input_visualizer_pack".equals(str(b,"format"))) throw new IOException("unsupported format"); if(num(b,"version",-1)!=1) throw new IOException("unsupported version"); for(String k:new String[]{"meta","settings","profile","theme"}) if(!b.has(k)||!b.get(k).isJsonObject()) throw new IOException("missing object: "+k); }
    private HashMap<String,LoadedPackTexture> registerTextures(HashMap<String,byte[]> bytes, Model.Layout layout){ HashMap<String,LoadedPackTexture> map=new HashMap<>(); for(Map.Entry<String,byte[]> e:bytes.entrySet()){ try{ BufferedImage img=ImageIO.read(new ByteArrayInputStream(e.getValue())); if(img==null) continue; if(img.getWidth()>1024||img.getHeight()>1024) LOG.info("large texture >1024: "+e.getKey()); if(img.getWidth()>=2048||img.getHeight()>=2048) LOG.warn("very large texture >=2048: "+e.getKey()); DynamicTexture dyn=new DynamicTexture(img); ResourceLocation loc=Minecraft.getMinecraft().getTextureManager().getDynamicTextureLocation("input_visualizer/pack_"+(textureSerial++), dyn); map.put(e.getKey(), new LoadedPackTexture(e.getKey(),loc,img.getWidth(),img.getHeight())); }catch(Exception ex){LOG.warn("texture load failed: "+e.getKey(),ex);} } markMissingImageFallback(layout.roots,map); return map; }
    private void markMissingImageFallback(List<Model.Element> els, Map<String,LoadedPackTexture> t){ for(Model.Element e:els){ if(e.kind==Model.ElementKind.MOUSE_PAD && e.mousePad.background.type==Model.BackgroundKind.IMAGE && !t.containsKey(e.mousePad.background.path)){ e.mousePad.background.type=Model.BackgroundKind.CHECKERBOARD; e.mousePad.background.fallbackCheckerboard=true; LOG.warn("image missing, checkerboard fallback: "+e.mousePad.background.path);} markMissingImageFallback(e.children,t);} }
    private byte[] readAll(InputStream in,int max)throws IOException{ ByteArrayOutputStream out=new ByteArrayOutputStream(); byte[] b=new byte[8192]; int n,total=0; while((n=in.read(b))!=-1){total+=n;if(total>max)throw new IOException("entry too large"); out.write(b,0,n);} return out.toByteArray(); }
    private String str(JsonObject o,String k){return o.has(k)&&!o.get(k).isJsonNull()?o.get(k).getAsString():"";} private int num(JsonObject o,String k,int d){return o.has(k)?o.get(k).getAsInt():d;}
    private String defaultBundle(){ return "{\n"+
        "  \"format\": \"input_visualizer_pack\",\n  \"version\": 1,\n  \"meta\": {\"id\":\"default_complete\",\"name\":\"Default Complete\",\"author\":\"Input Visualizer\"},\n"+
        "  \"settings\": {\"globalScale\":1,\"globalOffsetX\":0,\"globalOffsetY\":0,\"globalOpacity\":1},\n"+
        "  \"theme\": {\"tokens\": {\"keyFill\":\"#AA202020\",\"keyPressed\":\"#FFEFEFEF\"}, \"styles\": {\"keyBox\": {\"shape\":\"rounded_rectangle\",\"cornerRadius\":5,\"fillMode\":\"filled_outline\",\"borderWidth\":1,\"fontScale\":1,\"normal\":{\"fillColor\":\"$keyFill\",\"borderColor\":\"#CCFFFFFF\",\"textColor\":\"#FFFFFFFF\"},\"pressed\":{\"fillColor\":\"$keyPressed\",\"borderColor\":\"#FFFFFFFF\",\"textColor\":\"#FF101010\",\"glow\":{\"enabled\":true,\"color\":\"#FFFFFFFF\",\"alpha\":0.25,\"size\":5}},\"disabled\":{\"fillColor\":\"#AA552020\",\"borderColor\":\"#FFFF6666\",\"textColor\":\"#FFFFBBBB\"},\"pressAnimation\":{\"enabled\":true,\"type\":\"scale_offset\",\"durationMs\":90,\"scale\":0.94,\"offsetY\":0},\"releaseEffect\":{\"type\":\"glow_fade\",\"durationMs\":160}}}},\n"+
        "  \"profile\": {\"canvas\": {\"referenceWidth\":854,\"referenceHeight\":480}, \"elements\": [\n"+
        "    {\"type\":\"group\",\"id\":\"main\",\"anchor\":\"bottom_left\",\"x\":20,\"y\":-92,\"children\":[\n"+
        "      {\"type\":\"input\",\"styleRef\":\"keyBox\",\"x\":42,\"y\":0,\"width\":38,\"height\":22,\"label\":\"W\",\"input\":{\"type\":\"keyBinding\",\"name\":\"key.forward\"}},\n"+
        "      {\"type\":\"input\",\"styleRef\":\"keyBox\",\"x\":0,\"y\":26,\"width\":38,\"height\":22,\"label\":\"A\",\"input\":{\"type\":\"keyBinding\",\"name\":\"key.left\"}},\n"+
        "      {\"type\":\"input\",\"styleRef\":\"keyBox\",\"x\":42,\"y\":26,\"width\":38,\"height\":22,\"label\":\"S\",\"input\":{\"type\":\"keyBinding\",\"name\":\"key.back\"}},\n"+
        "      {\"type\":\"input\",\"styleRef\":\"keyBox\",\"x\":84,\"y\":26,\"width\":38,\"height\":22,\"label\":\"D\",\"input\":{\"type\":\"keyBinding\",\"name\":\"key.right\"}},\n"+
        "      {\"type\":\"mouse_button\",\"styleRef\":\"keyBox\",\"x\":132,\"y\":0,\"width\":44,\"height\":22,\"label\":\"LMB\",\"input\":{\"type\":\"mouseButton\",\"button\":\"left\"}},\n"+
        "      {\"type\":\"mouse_button\",\"styleRef\":\"keyBox\",\"x\":180,\"y\":0,\"width\":44,\"height\":22,\"label\":\"RMB\",\"input\":{\"type\":\"mouseButton\",\"button\":\"right\"}},\n"+
        "      {\"type\":\"mouse_pad\",\"id\":\"pad\",\"x\":132,\"y\":28,\"width\":92,\"height\":58,\"shape\":\"rounded_rectangle\",\"cornerRadius\":8,\"fillMode\":\"filled_outline\",\"fillColor\":\"#55202020\",\"borderColor\":\"#CCFFFFFF\",\"contentPadding\":4,\"background\":{\"type\":\"checkerboard\",\"cellSize\":8,\"scrollMode\":\"world\"},\"trail\":{\"enabled\":true,\"mode\":\"pan\",\"followMode\":\"instant\",\"resetMode\":\"center_on_empty\",\"smoothing\":\"catmull_rom\",\"lifetimeMs\":900,\"layers\":{\"glow\":true,\"line\":true,\"dots\":true,\"cursor\":true},\"colorMode\":\"button_state\"}}\n"+
        "    ]}\n  ]}\n}"; }
}
