package com.konqasasas.inputvisualizer.gui;

import com.konqasasas.inputvisualizer.config.*; import com.konqasasas.inputvisualizer.pack.VisualizerPackManager; import com.konqasasas.inputvisualizer.render.LayoutRenderer; import net.minecraft.client.gui.*; import java.awt.Desktop; import java.io.File; import java.util.*;

public final class GuiInputVisualizerSettings extends GuiScreen {
    private final VisualizerPackManager packs; private final VisualizerSettingsManager settings; private final LayoutRenderer renderer; private ArrayList<String> names=new ArrayList<>(); private int index=0; private String message="";
    public GuiInputVisualizerSettings(VisualizerPackManager p, VisualizerSettingsManager s, LayoutRenderer r){packs=p;settings=s;renderer=r;}
    public void initGui(){ names=packs.listPackNames(); index=Math.max(0,names.indexOf(settings.get().activePack)); buttonList.clear(); int c=width/2; buttonList.add(new GuiButton(1,c-135,yEnabled(),120,20,"Enabled: "+settings.get().enabled)); buttonList.add(new GuiButton(2,c+15,yEnabled(),120,20,"Reload")); buttonList.add(new GuiButton(3,c-145,yPackButtons(),90,20,"< Pack")); buttonList.add(new GuiButton(4,c-50,yPackButtons(),100,20,"Select")); buttonList.add(new GuiButton(5,c+55,yPackButtons(),90,20,"Pack >")); buttonList.add(new GuiButton(6,c-135,yActions(),120,20,"Open Folder")); buttonList.add(new GuiButton(7,c+15,yActions(),120,20,"Edit Groups")); buttonList.add(new GuiButton(8,c-50,height-28,100,20,"Done")); }
    private void addPair(int x,int y,int base,String label){ buttonList.add(new GuiButton(base+1,x,y,45,20,label+" -")); buttonList.add(new GuiButton(base+2,x+55,y,45,20,label+" +")); }
    protected void actionPerformed(GuiButton b){ VisualizerSettings s=settings.get(); if(b.id==1){s.enabled=!s.enabled;settings.save();initGui();} if(b.id==2){renderer.clearTransientState(); message=packs.reloadKeepingPrevious()?"Reloaded":"Reload failed: "+packs.lastError();} if(b.id==3&&!names.isEmpty()){index=(index+names.size()-1)%names.size();} if(b.id==5&&!names.isEmpty()){index=(index+1)%names.size();} if(b.id==4&&!names.isEmpty()){renderer.clearTransientState(); message=packs.selectPack(names.get(index))?"Selected: "+names.get(index):"Select failed"; settings.loadOrCreate(); initGui();} if(b.id==6){try{Desktop.getDesktop().open(new File(mc.mcDataDir,"input_visualizer/packs"));}catch(Exception e){message="Could not open folder";}} if(b.id==7){mc.displayGuiScreen(new GuiInputVisualizerGroupEditor(packs,settings,renderer,this));} if(b.id==8){settings.save(); mc.displayGuiScreen(null);} }
    public void drawScreen(int mx,int my,float pt){ drawDefaultBackground(); VisualizerSettings s=settings.get(); drawCenteredString(fontRenderer,"Input Visualizer Settings",width/2,18,0xFFFFFFFF); String p=names.isEmpty()?"(no .ivizpack found)":names.get(index); int max=Math.max(80,width-80); drawCenteredString(fontRenderer,"Active Pack:",width/2,yActiveLabel(),0xFFCCCCCC); drawCenteredString(fontRenderer,fitText(s.activePack,max),width/2,yActiveName(),0xFFEAF6FF); drawCenteredString(fontRenderer,"Candidate: "+fitText(p,Math.max(80,width-120)),width/2,yCandidate(),0xFFCCCCCC); if(!message.isEmpty()) drawCenteredString(fontRenderer,message,width/2,height-44,0xFFFFFF88); super.drawScreen(mx,my,pt); }
    private int yEnabled(){return 48;} private int yActiveLabel(){return 86;} private int yActiveName(){return 102;} private int yPackButtons(){return 124;} private int yCandidate(){return 154;} private int yActions(){return 176;}
    private String fitText(String s,int maxWidth){ if(s==null)return ""; if(fontRenderer.getStringWidth(s)<=maxWidth)return s; String suffix="..."; String out=s; while(out.length()>0&&fontRenderer.getStringWidth(out+suffix)>maxWidth) out=out.substring(0,out.length()-1); return out+suffix; }
    public boolean doesGuiPauseGame(){return false;}
}
